### PR TITLE
Added closed-loop functionality, polling more motor status bits

### PR DESCRIPTION
**Pull request by ArtaChris**
Successfully tested with both 8742, 8743-CL controllers, 8310 and 8410 picomotors.
Added detection between 8742 & 8743-CL, 8310/8310-V & 8410.
Added closed-loop configuration with 8743-CL.
Added set soft high/low limits.
Added update interval, deadband, following error parameters, mutator functions.
Changed home function to use commands that move motor to index.
Changed poll to update bits: direction, high limit, low limit, home switch, home position, closed-loop enable, encoder is present, gain support.

### CODE REVIEW

**Comment by kmpeters** [comment]
Thanks for these improvements!

**Comment by kmpeters** [comment]
@ArtaChris, do you know which firmware versions are on the controllers you used for testing.  A problem has been reported with this pull request that gives me the impression some of the commands it uses aren't available on older firmware versions.

**Comment by ArtaChris** [comment]
@kmpeters
For 8742 Controller:
New_Focus 8742 v3.04 09/09/16 38423
For 2 8743-CL Controllers:
New_Focus 8743-CL v4.06 01/19/17 11181
New_Focus 8743-CL v4.06 01/19/17 11047
We were using EPICS 3.14.12.7

**Comment by kmpeters** [comment]
Thanks!

**Pull request merged**
